// FitnesGym — Tema canónico de toda la app (mismo config que el dashboard "Inicio").
// Cada página debe cargar este archivo ANTES del script de Tailwind CDN:
//   <script src="../js/theme.js"></script>
//   <script>tailwind.config = window.FITNESSGYM_THEME;</script>
//   <script src="https://cdn.tailwindcss.com"></script>
window.FITNESSGYM_THEME = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#1b1b1e',
        'surface-dim': '#131316',
        'on-surface-variant': '#bbcabf',
        'primary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-fixed': '#ffddb8',
        'surface-tint': '#4edea3',
        'secondary-fixed-dim': '#ffb3ad',
        'on-secondary-fixed-variant': '#930013',
        'on-secondary': '#68000a',
        'on-primary': '#003824',
        'on-tertiary-container': '#523200',
        'secondary-fixed': '#ffdad7',
        'surface-container-high': '#2a2a2d',
        'on-tertiary-fixed-variant': '#653e00',
        error: '#ffb4ab',
        'on-tertiary': '#472a00',
        secondary: '#ffb3ad',
        'surface-bright': '#39393c',
        primary: '#4edea3',
        'on-background': '#e4e1e6',
        'primary-container': '#10b981',
        'on-primary-fixed': '#002113',
        'on-tertiary-fixed': '#2a1700',
        'surface-variant': '#353438',
        'inverse-surface': '#e4e1e6',
        'on-primary-fixed-variant': '#005236',
        'on-secondary-fixed': '#410004',
        'surface-container-lowest': '#0e0e11',
        outline: '#86948a',
        'inverse-primary': '#006c49',
        'on-error': '#690005',
        'surface-container': '#1f1f22',
        'secondary-container': '#a40217',
        'on-error-container': '#ffdad6',
        'outline-variant': '#3c4a42',
        'inverse-on-surface': '#303033',
        'tertiary-container': '#e29100',
        'on-secondary-container': '#ffaea8',
        tertiary: '#ffb95f',
        'primary-fixed-dim': '#4edea3',
        surface: '#131316',
        background: '#131316',
        'on-surface': '#e4e1e6',
        'on-primary-container': '#00422b',
        'surface-container-highest': '#353438',
        'error-container': '#93000a',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'space-md': '1rem', 'space-xl': '2.5rem', gutter: '1rem', 'margin-desktop': '2rem',
        'space-xs': '0.25rem', margin: '1rem', 'space-sm': '0.5rem', 'gutter-desktop': '1.5rem', 'space-lg': '1.5rem',
      },
      fontFamily: {
        'body-md': ['Inter'], 'headline-xl-mobile': ['Plus Jakarta Sans'], 'body-lg': ['Inter'],
        'headline-lg': ['Plus Jakarta Sans'], 'headline-xl': ['Plus Jakarta Sans'], 'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'], 'headline-md': ['Plus Jakarta Sans'], 'body-sm': ['Inter'],
        'label-sm': ['Inter'], 'label-md': ['Inter'], 'label-lg': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-xl-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
};